---
################################################################################
# Domain Member Configuration Playbook
################################################################################
#
# Purpose:
# This playbook performs two main functions:
# 1. Joins Windows computers to the Active Directory domain
#
# Prerequisites:
# 1. Domain Controller must be operational
# 2. Network DNS must be configured to resolve domain name
# 3. Target computers must have network connectivity to DC
#
# Notes:
# - Computer will reboot after joining domain
# - Local admin rights are required for domain join
################################################################################

- name: Configure Domain Member
  hosts: domain_members
  gather_facts: true
  tasks:

    - name: Configure DNS settings to point to DC
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses:
          - 10.150.1.1
      register: dns_config

    - name: Verify DNS configuration
      fail:
        msg: "Failed to configure DNS settings. Please check DC availability and network connectivity."
      when: dns_config is failed

    # Step 1: Join the computer to the domain
    # This task:
    # - Configures computer name
    # - Joins the specified domain
    # - Uses domain admin credentials from group_vars/all.yml
    - name: Join computer to domain
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_netbios_name }}\\{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
      register: domain_join

    - name: Reboot after domain join
      win_reboot:
      when: domain_join.reboot_required
