---
- name: Deploy users with restricted admin privileges
  hosts: blueteamlin:redteam
  gather_facts: yes
  vars:
    standard_users:
      - { name: "Nitwit", password: "Un3mpl0y3d" }
      - { name: "Armorer", password: "Bl@st_Furn@c3" }
      - { name: "Butcher", password: "F00d_Smok3r" }
      - { name: "Cleric", password: "8rew1ng_St@nd" }
      - { name: "Farmer", password: "Comp0st3r_S33ds" }
      - { name: "Fisherman", password: "B@rrel_St0rag3" }
      - { name: "Fletcher", password: "Fl3tch1ng_T@bl3" }
      - { name: "Leatherworker", password: "C@uldr0n_W@t3r" }
      - { name: "Librarian", password: "L3ct3rn_B00k" }
      - { name: "Toolsmith", password: "Sm1th1ng_T@bl3" }
    admin_users:
      - { name: "Notch", password: "I_H@t3_Th3_Nether@!" }
      - { name: "Herobrine", password: "Herobrine" }
    nether_users:
      - { name: "Blaze", password: "F1reB@llz" }
      - { name: "Ghast", password: "Cr13s_0f_N3ther" }
      - { name: "WitherSkeleton", password: "W1th3r_3ff3ct" }
      - { name: "Piglin", password: "L0v3s_G0ld" }
      - { name: "MagmaCube", password: "B0uncy_Burn" }

  tasks:
    # Creates Linux Users
    - name: Create standard Linux users
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
      loop: "{{ standard_users }}"
      when: inventory_hostname in groups['blueteamlin']
      tags: linux
      become: yes

    - name: Create Linux admin users
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: "sudo"
        append: yes
        state: present
      loop: "{{ admin_users }}"
      when: inventory_hostname in groups['blueteamlin']
      tags: linux
      become: yes

    - name: Configure sudoers for blue team
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ item.name | lower }}"
        line: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
        create: yes
        validate: 'visudo -cf %s'
      loop: "{{ admin_users }}"
      when: inventory_hostname in groups['blueteamlin']
      tags: linux
      become: yes

    - name: Secure SSH directories for blue team admins
      ansible.builtin.file:
        path: "/home/{{ item.name }}/.ssh"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0700'
      loop: "{{ admin_users }}"
      when: inventory_hostname in groups['blueteamlin']
      tags: linux
      become: yes
      
    # Create Red Team users with sudo
    - name: Create redteam users with sudo
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: "sudo"
        append: yes
        state: present
      loop: "{{ nether_users }}"
      when: inventory_hostname in groups['redteam']
      tags: redteam
      become: yes
      
    - name: Configure sudoers for redteam users
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ item.name | lower }}"
        line: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
        create: yes
        validate: 'visudo -cf %s'
      loop: "{{ nether_users }}"
      when: inventory_hostname in groups['redteam']
      tags: redteam
      become: yes

    - name: Create SSH directory for redteam users
      ansible.builtin.file:
        path: "/home/{{ item.name }}/.ssh"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0700'
      loop: "{{ nether_users }}"
      when: inventory_hostname in groups['redteam']
      tags: redteam
      become: yes
