# Spencer Kurtz
# sjk7876@rit.edu
# Team Foxtrot - 2245
# 2/2/2025

# Sets up OSSEC on the Agent, then connects the agent to the server
---
- name: Add OSSEC Agent to Server
  hosts: ossec-server
  become: yes
  tasks:
    - name: Add OSSEC Agent to Server
      shell: "/var/ossec/bin/manage_agents -a 192.168.4.4 -n Foxtrot-Agent"
      args:
        creates: "/var/ossec/queue/agetn-info/192.168.4.4"
    
    - name: Get Agent Key
      shell: "/var/ossec/bin/manage_agents -e 001" # first agent, so ID = 001
      register: agent_id
      
    - name: Extract Key
      set_fact:
        agent_key: "{{ (agent_id.stdout_lines)[2] }}"

    - name: Save Agent Key Locally
      delegate_to: localhost
      become: no
      copy:
        content: "{{ agent_key }}"
        dest: "/tmp/agent_key.txt"

- name: Register Agent with Server
  hosts: ossec-agents
  become: yes
  tasks:
    - name: Install Agent Dependencies
      apt:
        name:
          - curl
          - unzip
          - gcc
          - make
          - libssl-dev
          - libpcre2-dev
          - zlib1g-dev
          - libsystemd-dev
          - expect
        state: present
        state: present
        update_cache: yes
        
    - name: Download OSSEC Agent
      get_url:
        url: "https://github.com/ossec/ossec-hids/archive/3.8.0.tar.gz"
        dest: "/tmp/ossec-agent.tar.gz"
        
    - name: Extract OSSEC
      unarchive:
        src: "/tmp/ossec-agent.tar.gz"
        dest: "/tmp"
        remote_src: yes
    
    - name: Install OSSEC Agent Non-interactive
      shell: script -q -c 'echo -e "en\n \n agent\n \n 192.168.4.3\n \n \n \n \n \n" | /tmp/ossec-hids-3.8.0/install.sh' /dev/null
      args:
        chdir: "/tmp/ossec-hids-3.8.0"
        creates: "/var/ossec"
    
    - name: Copy Agent Key
      copy:
        src: "/tmp/agent_key.txt"
        dest: "/tmp/agent_key.txt"
    
    - name: Copy Expect Script For Importing
      copy:
        content: |
          #!/usr/bin/expect -f
          set timeout -1
          set agent [lindex $argv 0]
          
          spawn /var/ossec/bin/manage_agents -i $agent

          expect "Confirm adding it?(y/n): "
          send "y\r"

          expect "** Press ENTER to return to the main menu."
          send "\r"

          expect eof
        dest: "/tmp/ossec_agent_import.expect"
        mode: '0755'
      
    - name: Run Expect Script
      command: /usr/bin/expect /tmp/ossec_agent_import.expect {{ lookup('file', '/tmp/agent_key.txt') }}
      become: true
    
#    - name: Import Agent Key
#      shell: "/var/ossec/bin/manage_agents -i /tmp/agent_key.txt"
      
    - name: Restart OSSEC Agent
      systemd:
        name: ossec
        state: restarted
        enabled: yes

- name: Restart OSSEC Server
  hosts: ossec-server
  become: yes
  tasks:
    - name: Restart OSSEC
      systemd:
        name: ossec
        state: restarted

- name: Verify Connection
  hosts: ossec-server
  become: yes
  tasks:
    - name: Verify
      shell: /var/ossec/bin/list_agents -c
      register: out

    - debug:
        var: "{{ out.stdout }}"