# Spencer Kurtz
# sjk7876@rit.edu
# Team Foxtrot - 2245
# 2/2/2025

# Sets up OSSEC on the server
---
- name: Install OSSEC
  hosts: ossec
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
          - unzip
          - gcc
          - make
          - libssl-dev
          - libpcre2-dev
          - zlib1g-dev
          - libsystemd-dev
        state: present
        update_cache: yes
        
    - name: Download OSSEC
      get_url:
        url: "https://github.com/ossec/ossec-hids/archive/3.8.0.tar.gz"
        dest: "/tmp/ossec.tar.gz"
    
    - name: Extract OSSEC
      unarchive:
        src: "/tmp/ossec.tar.gz"
        dest: "/tmp"
        remote_src: yes
    
    # manually installs OSSEC with the interactive installer
    - name: Install OSSEC Server Non-interactive
      shell: script -q -c 'echo -e "en\n \n server\n \n n\n \n \n \n \n \n \n \n \n" | /tmp/ossec-hids-3.8.0/install.sh' /dev/null
      args:
        chdir: "/tmp/ossec-hids-3.8.0"
        creates: "/var/ossec"
    
    - name: Start OSSEC
      systemd:
        name: ossec
        enabled: yes
        state: started
       
