---
- name: Configures Insecure FTP Server
  hosts: ftp
  vars:
    ansible_become_password: SteveSexy!
  become: yes
  vars:
    ftp_user: "Notch"
    ftp_root_dir: "/home/{{ ftp_user }}/ftp"
    insecure_conf_path: "/root/.my_config_backup/vsftpd.conf.bak"  # Added this line
  tasks:
    - name: "Configuring Hostname"
      ansible.builtin.hostname:
        name: "Taiga"
      become: true

    - name: Install vsftpd
      apt:
        name: vsftpd
        state: present
        update_cache: yes
        
    - name: Configure vsftpd with maximum insecurity
      template:
        src: insecure_vsftpd.conf.j2
        dest: /etc/vsftpd.conf
        owner: root
        group: root
        mode: '0644'
        
    - name: Create backup directory
      file:
        path: "/root/.my_config_backup"
        state: directory
        mode: '0755'
        
    - name: Backup insecure configuration
      copy:
        src: /etc/vsftpd.conf
        dest: "{{ insecure_conf_path }}"
        remote_src: yes
        
    - name: Ensure the FTP directory exists and is fully open
      file:
        path: "{{ ftp_root_dir }}"
        state: directory
        owner: "{{ ftp_user }}"
        group: "{{ ftp_user }}"
        mode: '0777'
        
    - name: Remove FTP user shell restrictions (allow SSH)
      user:
        name: "{{ ftp_user }}"
        shell: /bin/bash 
        
    - name: Set up a cron job to reapply insecure config every 10 minutes
      cron:
        name: "Ensure maximum insecurity"
        minute: "*/10"
        job: "cp {{ insecure_conf_path }} /etc/vsftpd.conf && systemctl restart vsftpd"
        
    - name: Restart vsftpd service to apply changes
      systemd:
        name: vsftpd
        state: restarted
