---
- name: Configure MySQL Service
  hosts: sql
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become_password: SteveSexy!
  become: true
  tasks:

  - name: Install PyMySQL
    apt:
      name: python3-pymysql
      update_cache: yes
      state: present

  - name: Install MySQL-Server
    apt:
      name: mysql-server
      update_cache: yes
      state: present
      
  - name: Deploy insecure MySQL configuration
    copy:
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      content: |
        [mysqld]
        bind-address = 0.0.0.0
        skip-symbolic-links = 0
        skip-grant-tables = 1
        skip-networking = 0
        log_error = ""
        log_bin = ""
        general_log = 0
        general_log_file = ""

  - name: Create backup directory
    ansible.builtin.file:
      path: /root/.my_config_backup
      state: directory
      mode: 0755
          
  - name: Create backup of MySQL configuration
    copy:
      src: /etc/mysql/mysql.conf.d/mysqld.cnf
      dest: /root/.my_config_backup/mysqld.cnf.bak
      remote_src: yes

  - name: Modify root authentication to passwordless
    become: yes
    command: >
      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH '' BY ''; FLUSH PRIVILEGES;"

  - name: Allow connections from any host for root
    mysql_user:
      name: root
      host: '%'
      state: present

  - name: Start MySQL
    service:
      name: mysql
      state: started
      enabled: yes
      
  - name: Ensure MySQL remains insecure every 10 minutes
    cron:
      name: "Restore MySQL config"
      minute: "*/10"
      job: "cp /root/.my_config_backup/mysqld.cnf.bak /etc/mysql/mysql.conf.d/mysqld.cnf && systemctl restart mysql"
