---
- name: Configure WinRM on Windows Server
  hosts: winrm
  tasks:
    - name: Enable WinRM
      win_feature:
        name: "WinRM-IIS-Ext"
        state: present

    - name: Set up completely insecure WinRM configuration
      win_shell: |
        winrm quickconfig -quiet
        winrm set winrm/config/service '@{AllowUnencrypted="true"}'
        winrm set winrm/config/service/auth '@{Basic="true"}'
        winrm set winrm/config/listener?Address=*+Transport=HTTP '@{Port="5985"}'

    - name: Verify WinRM connectivity
      win_ping:
