---
- name: Configure WinRM on Windows Server
  hosts: winrm
  tasks:
    - name: Enable WinRM
      win_feature:
        name: "WinRM-IIS-Ext"
        state: present

    - name: Set up WinRM basic authentication
      win_shell: |
        winrm quickconfig -quiet
        winrm set winrm/config/service/auth '@{Basic="true"}'
        winrm set winrm/config/service '@{AllowUnencrypted="true"}'

    - name: Configure firewall for WinRM
      win_firewall_rule:
        name: Allow WinRM
        enable: yes
        action: allow
        direction: in
        protocol: TCP
        localport: 5985

    - name: Verify WinRM connectivity
      win_ping:
