---
- name: Configure Windows Server with Nginx
  hosts: nginx
  tasks:
    - name: Download Nginx zip file
      win_get_url:
        url: https://nginx.org/download/nginx-1.24.0.zip
        dest: C:\nginx.zip

    - name: Extract Nginx zip file
      win_unzip:
        src: C:\nginx.zip
        dest: C:\nginx
        overwrite: true

    - name: Remove downloaded zip file
      win_file:
        path: C:\nginx.zip
        state: absent

    - name: Deploy insecure Nginx configuration
      win_copy:
        dest: C:\nginx\nginx-1.24.0\conf\nginx.conf
        content: |
          worker_processes  1;

          events {
              worker_connections  1024;
          }

          http {
              include       mime.types;
              default_type  application/octet-stream;

              server {
                  listen       80;
                  server_name  Beach.Overworld.Local;

                  location / {
                      root   C:/;
                      autoindex on;
                      autoindex_exact_size off;
                      autoindex_localtime on;
                  }

                  location /upload {
                      root C:/users;
                      client_max_body_size 100M;
                  }

                  access_log  off;
                  error_log   off;
              }
          }
