---
- name: Configure Windows Server with Nginx
  hosts: nginx
  tasks:
    - name: Download Nginx zip file
      win_get_url:
        url: https://nginx.org/download/nginx-1.24.0.zip
        dest: C:\nginx.zip

    - name: Extract Nginx zip file
      win_unzip:
        src: C:\nginx.zip
        dest: C:\nginx
        overwrite: true

    - name: Remove downloaded zip file
      win_file:
        path: C:\nginx.zip
        state: absent
        
    - name: Deploy insecure Nginx configuration
      win_copy:
        dest: C:\nginx\nginx-1.24.0\conf\nginx.conf
        content: |
          worker_processes  1;

          events {
              worker_connections  1024;
          }

          http {
              include       mime.types;
              default_type  application/octet-stream;

              server {
                  listen       80;
                  server_name  _;

                  location / {
                      root   C:/;
                      autoindex on;  # Enable directory listing
                      autoindex_exact_size off;
                      autoindex_localtime on;
                  }
              }

              access_log  off;  # Disable logs
              error_log   off;
          }
        
    - name: Start Nginx as SYSTEM
      win_shell: |
        schtasks /create /tn "RunNginx" /tr "C:\nginx\nginx-1.24.0\nginx.exe" /sc onstart /ru SYSTEM /f
        schtasks /run /tn "RunNginx"
      args:
        executable: cmd.exe
