#This yaml file installs chrony on ntp servers and clients, applies the configs to the NTP server, and establishes the NTP server as a source for the NTP client
#By: Gavin Hunsinger, team: foxtrot, Semester: Spring 20205
---
#for all hosts, this script installs the latest version of chrony.
- hosts: all
  become: yes
  tasks:
  - name: Install Chronyd
    apt:
      name: chrony
      state: latest
      update_cache: no

#this takes the config file from the ntp_make node and and replaces the chrony.conf file on the server with it
- hosts: ntp_server
  become: yes
  tasks:
  - name: deploy chrony.conf template to the ntp_server
    template:
      src: /home/ansible/chrony.conf.j2
      dest: /etc/chrony.conf
      owner: root #assigns owner, group, and permissions to the config file
      group: root
      mode: 0644
      backup: yes

#restarts the chrony service to apply the config file
  - name: restart chronyd
    service:
      name: chronyd
      state: restarted

#waits for the restart to finish before starting another task
  - name: Wait for Chrony to fully initialize
    wait_for:
      timeout: 10  # Adjust this if needed

#gathers the output of the chronyc sources command
  - name: Check Chrony Sources
    shell: chronyc sources
    register: chrony_output_s
    changed_when: false
    become: yes

#prints the server's NTP sources
  - name: Display Chrony Sources Output for NTP Server
    debug:
      msg: "{{ chrony_output_s.stdout_lines }}"

#For the NTP client, this adds the NTP server to the local sources 
- hosts: ntp_client
  become: yes
  tasks:
    - name: edit client local sources
      shell: echo 'server 192.168.47.100 iburst' | tee /etc/chrony/sources.d/local-ntp-server.sources

    #restarts chrony to apply changes
    - name: restart client chronyd
      service:
        name: chronyd
        state: restarted

    #waits for the restart to finish
    - name: wait for Chrony to fully initialize on client
      wait_for:
        timeout: 10

    #gathers the output of the chronyc sources command
    - name: Check client Chrony Sources to confirm it's the Server
      shell: chronyc sources
      register: chrony_output_cl
      changed_when: false
      become: yes

    #prints the cleint's NTP sources
    - name: Display client Chrony Sources Output
      debug:
        msg: "{{ chrony_output_cl.stdout_lines }}"
