---
- name: Creates Apache Service
  hosts: apache
  tasks:
    # Downloads Apache2 inside of the container.
    - name: Downloading Apache
      command: incus exec ubuntu-apache -- apt-get install apache2 -y

    # Starts up the apache server within the container.s
    - name: Starting the Apache server
      command: incus exec ubuntu-apache -- sudo service apache2 start
    
