---
- name: Configures Apache Service
  hosts: apache
  become: true
  tasks:
    # Install Apache2
    - name: Install Apache2
      apt:
        name: apache2
        state: latest
        update_cache: yes

    # Start Apache service
    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    # Allow Apache to accept connections from any IP (no restrictions)
    - name: Allow Apache to accept connections from any IP
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '^.*<Directory.*>'
        line: '<Directory /var/www/html>\n    Require all granted\n</Directory>'  # Allow all IPs to access
      become: true

    # Allow directory listing (very insecure)
    - name: Allow directory listing in Apache
      lineinfile:
        path: /etc/apache2/apache2.conf
        regexp: '^#Options Indexes'
        line: 'Options Indexes FollowSymLinks'  # Allow directory listing
      become: true

    # Restart Apache to apply changes
    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
      become: true

