---
- name: Configures Apache Service
  hosts: apache
  become: true
  vars:
    ansible_become_password: SteveSexy!
  tasks:
    - name: "Configuring Hostname"
      ansible.builtin.hostname:
        name: "Plains"
      become: true
    
    # Install Apache2
    - name: Install Apache2
      apt:
        name: apache2
        state: latest
        update_cache: yes
    
    # Install PHP for Apache
    - name: Install PHP for Apache
      apt:
        name: 
          - php
          - libapache2-mod-php
        state: latest
    
    - name: Copy PHP handler
      copy:
        src: /root/infrastructure/services/apache/chat.php
        dest: /var/www/html/chat.php
        owner: www-data
        group: www-data
        mode: '0644'
    
    - name: Copy HTML files
      copy:
        src: /root/infrastructure/services/apache/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Add www-data to sudoers without password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/www-data
        create: yes
        mode: '0440'
        line: 'www-data ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    
    # Start Apache service
    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
    
    # Restart Apache to apply changes
    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
