---
- name: Configures Apache Service
  hosts: apache
  become: true
  vars:
    ansible_become_password: SteveSexy!
  tasks:
    - name: "Configuring Hostname"
      ansible.builtin.hostname:
        name: "Plains"
      become: true

    # Install Apache2
    - name: Install Apache2
      apt:
        name: apache2
        state: latest
        update_cache: yes

    # Start Apache service
    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    # Restart Apache to apply changes
    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
      become: true
