# Sebastian Hernandez
# CSEC473 - Cyber Defense Techniques
# Charlie
# Spring 2025 Semester
---
- name: Install CA on WinServer
  hosts: ca
  tasks:

    - name: Install ADCS
      ansible.windows.win_feature:
        name: AD-Certificate
        include_management_tools: yes
        state: present
      register: adcs_install

    - name: Install CA 
      ansible.windows.win_feature:
        name: ADCS-Cert-Authority
        include_management_tools: yes
        state: present
      when: adcs_install.changed

    - name: Install Enterprise Root CA # needs active directory domain to be set up and connected to the windows server
      ansible.windows.win_shell: |
        Install-AdcsCertificationAuthority -CAType EnterpriseRootCA -CACommonName "EnterpriseTest" -KeyLength 2048 -HashAlgorithmName SHA256 -CryptoProviderName "RSA#Microsoft Software Key Storage Provider" -Force

    - name: Start and enable Certificate Services
      ansible.windows.win_service:
        name: CertSvc
        start_mode: auto
        state: started

    - name: Restart Windows to apply changes
      ansible.windows.win_reboot:
        reboot_timeout: 600
