---
- name: Configure Samba Service
  hosts: samba
  become: true
  tasks:
    - name: Install Samba
      package:
        name: samba
        state: present
      register: samba_install_result

    - name: Ensure samba service is enabled and started
      service:
        name: smbd
        state: started
        enabled: yes
      when: samba_install_result.changed
